name: Run tests
on:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo "Check out last commit 🔎"
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: echo "Install dependencies 💾"
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
 
    - name: echo "Run Black formatting ✨"
      run: black src

    - name: echo "Run flake8 📋"
      run: flake8 --count --show-source --statistics src
